version: '3.8'

services:
  php:
    container_name: starting_script
    restart: always
    depends_on:
      - "server"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/

  server:
    image: redis
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - redis-data:/var/lib/redis

volumes:
  redis-data: